image: python:3

stages:
  - linting
  - unit
  - functional

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install pylint
  - pip install -r requirements.txt

lint-testing:
  stage: linting
  script:
    - pylint --fail-under=-3 alphagradient/*

unit-test-standard.py:
  stage: unit
  script:
    - python3 test/test_utils.py
    - python3 test/test_data.py
    - python3 test/test_asset.py
    - python3 test/test_portfolio.py
    - python3 test/test_algorithm.py
    - python3 test/test_collections.py
    - python3 test/test_globals.py
