image: python:3

stages:
  - linting
  - unit
  - functional

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install flake8
  - pip install -r requirements.txt

lint-testing:
  stage: linting
  script:
    - flake8 AlphaGradient/finance/standard.py --verbose

unit-test-standard.py:
  stage: unit
  script:
    - python3 tests.unit_test.py
